config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  resources :posts 
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
   
    validates :title, :author, :body, presence: true

    has_many:comments

    friendly_id :title, use: :slugged
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create!(comments_params)

    redirect_to comment.post, notice: 'O seu comentário foi enviado.'
  end

  private

  def comments_params
    params.require(:comment).permit(:post_id, :author, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <div class="bg-primary text-white text-center mb-4 p-4">
  <%= link_to root_path, class: 'text-white text-decoration-none' do %>
    <h1 class="display-4">Blog Teste</h1>   
  <% end %>
   <p class="lead">
    Texto lorem Texto lorem Texto lorem Texto lorem Texto lorem Texto lorem Texto lorem</p>
  </div>
  <div class="container">
   <% flash.each do |type, message| %>
        <div class='alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show' role='alert'>
          <%= message %>
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>  
    <%= yield %>  
  </div>
  

  <footer class="bg-primary text-white text-center mt-5 p-4">
  Copyright Blog rails <%= Date.current.year%>
  </footer>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 5 %>
  </div>

  <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Criando...' } %>
<% end %>

app/views/posts/_post.html.erb
<div class="card bg-light mb-3">
    <div class="card-body">
        <h4>
            <%= link_to post.title, post_path(post) %>
        </h4>
        <div class="text-muted mb-2">
            <em>Por <%= post.author%> (<%= l post.created_at, format: :short %>)</em>
        </div>
        <p>
            <%= post.body.truncate(50)%>
        </p>
        <p class="text-muted">
            <%= pluralize(post.comments.count, 'Comentário') %> 
        </p>

        <%= link_to "Ler Artigo", post, class: 'btn btn-primary' %>
        <%= link_to "Editar Artigo", edit_post_path(post), class: 'btn btn-warning' %>
        <%= link_to "Apagar Artigo", post, method: :delete, class: 'btn btn-danger',
        data: {confirm: 'Você tem certeza?'} %>
    </div>


</div>

app/views/posts/edit.html.erb
<h1>Editar Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%# <%= @posts.each do |post| %>
  <%# <%= render 'post', post: post %>
<%# <% end %>

<div class="d-flex justify-content-end">
  <%= link_to "Criar novo post", new_post_path, class: "btn btn-success mb-4" %>
</div>

<%= render @posts %>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form', post: @post %>

<%# <%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class='shadow bg-light p-5 rounded'>
  <div class='text-center mb-5'>
    <h1><%= @post.title %></h1>

    <p class='text-muted'>
      <strong>Por <%= @post.author %></strong><br>
      <%= l @post.created_at, format: :long %>
    </p>
  </div>

  <div class='px-5'>
    <%# ATENÇÃO: Sempre que usarmos \n (como na linha abaixo), precisamos usar áspas duplas %>
    <%= @post.body.gsub("\n", '<br>').html_safe %>
  </div>
</div>

<div class='m-5'>
  <div class='text-center'>
    <h4>
      <%= pluralize(@post.comments.count, 'Comentário') %>
      <% if @post.comments.none? %>
        <span class='badge badge-success'>Seja o primeiro a comentar!</span>
      <% end %>
    </h4>
  </div>

  <div class='shadow-sm m-3 p-3 bg-light rounded'>
    <%= form_with model: @comment, local: true do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>

      <div class='form-group'>
        <%= form.label :author %>
        <%= form.text_field :author, class: 'form-control', required: true %>
      </div>

      <div class='form-group'>
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', required: true %>
      </div>

      <%= form.submit 'Enviar', class: 'btn btn-primary',
        data: { disable_with: 'Enviando...' } %>
    <% end %>
  </div>

  <% @comments.each do |comment| %>
    <div class='shadow-sm m-3 p-3 bg-light rounded'>
      <div class='row'>
        <div class='col'>
          <strong><%= comment.author %></strong>
        </div>

        <div class='col text-right'>
          <em data-toggle='tooltip' data-placement='top' title='<%= l comment.created_at, format: :long %>'>
            <%= time_ago_in_words comment.created_at %> atrás
          </em>
        </button>
        </div>
      </div>

      <hr>

      <%# ATENÇÃO: Sempre que usarmos \n (como na linha abaixo), precisamos usar áspas duplas %>
      <%= sanitize(comment.body.gsub("\n", '<br>')).html_safe %>
    </div>
  <% end %>
</div>